#开发环境
server:
  port: 8088
mybatis:
  type-aliases-package: com.willi.wl.bean
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/WL?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 19961127